import io
import matplotlib.pyplot as plt
from fpdf import FPDF
import yfinance as yf
import pandas as pd
from typing import List, Dict
import tempfile
import os

class SimplePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, f'Good Morning Boss — {self.date_str}', ln=1, align='C')
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by Good Morning Boss - Executive Edition', 0, 0, 'C')

def build_price_plot(ticker: str, days: int = 365) -> Optional[io.BytesIO]:
    df = yf.download(ticker, period=f'{days}d', interval='1d', progress=False)
    if df.empty:
        return None
    close = df['Close']
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(close.index, close.values)
    ax.set_title(f'{ticker} price ({days}d)')
    ax.grid(True)
    buf = io.BytesIO()
    fig.tight_layout()
    fig.savefig(buf, format='png')
    plt.close(fig)
    buf.seek(0)
    return buf

def assemble_pdf_advanced(filename: str, tickers: List[str], portfolio: Dict, macro: Dict, report_df: pd.DataFrame, news_bundle: Dict):
    pdf = SimplePDF()
    pdf.date_str = report_df.index.name if not report_df.empty else 'Date'  # Placeholder
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Daily Executive Portfolio Report', ln=1)
    pdf.ln(4)
    # Macro
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 6, 'Macro snapshot:', ln=1)
    for k, v in macro.items():
        pdf.cell(0, 6, f'{k}: {v.get("last")}', ln=1)
    pdf.ln(4)
    # Portfolio table
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 6, 'Portfolio Overview', ln=1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(30, 6, 'Ticker', 1)
    pdf.cell(30, 6, 'Shares', 1)
    pdf.cell(30, 6, 'Buy Price', 1)
    pdf.cell(30, 6, 'Market Price', 1)
    pdf.cell(30, 6, 'Market Value', 1)
    pdf.ln(6)
    total_cost = total_mv = 0
    for t in tickers:
        s = portfolio.get(t, {}).get('shares', 0)
        b = portfolio.get(t, {}).get('buy_price', 0)
        p = report_df.loc[t, 'price'] if t in report_df.index else 0
        mv = p * s
        total_cost += s * b
        total_mv += mv
        pdf.cell(30, 6, t, 1)
        pdf.cell(30, 6, str(s), 1)
        pdf.cell(30, 6, str(b), 1)
        pdf.cell(30, 6, str(round(p, 2)) if p else 'N/A', 1)
        pdf.cell(30, 6, str(round(mv, 2)), 1)
        pdf.ln(6)
    # Per-asset
    for t in tickers:
        pdf.add_page()
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 6, f'Asset: {t}', ln=1)
        stats = report_df.loc[t] if t in report_df.index else {}
        pdf.set_font('Arial', '', 10)
        for k in ['current_price', '52w_high', '52w_low', 'vol_30d_ann', 'vol_90d_ann']:
            pdf.cell(0, 5, f'{k}: {stats.get(k)}', ln=1)
        # News
        headlines = news_bundle.get(t, {}).get('headlines', [])
        if headlines:
            pdf.set_font('Arial', 'B', 11)
            pdf.cell(0, 6, 'Recent Headlines:', ln=1)
            pdf.set_font('Arial', '', 9)
            for title, link in headlines[:6]:
                pdf.multi_cell(0, 5, f'- {title} ({link})')
        # Plot
        plotbuf = build_price_plot(t, days=365)
        if plotbuf:
            with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp:
                tmp.write(plotbuf.read())
                tmp_path = tmp.name
            pdf.image(tmp_path, w=180)
            os.unlink(tmp_path)  # Clean up
    # PnL summary
    pdf.add_page()
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 8, 'Total PnL Summary', ln=1)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 6, f'Total cost basis: ${total_cost:,.2f}', ln=1)
    pdf.cell(0, 6, f'Total market value: ${total_mv:,.2f}', ln=1)
    pdf.cell(0, 6, f'Total P&L: ${total_mv - total_cost:,.2f}', ln=1)
    pdf.output(filename)